### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by termosa** [HenrikJoreteg/feather-app#8]
I receive this error on `npm start`.

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/stylus-loader!./src/styles/main.styl
Module build failed: TypeError: /Users/termosa/Source/feather-app/src/styles/main.styl:3:1
   1| @import './globals/_variables'
   2| @import './globals/document'
   3|
------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:1433:5)
    at new SourceMapper (/Users/termosa/Source/feather-app/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
    at Renderer.render (/Users/termosa/Source/feather-app/node_modules/stylus/lib/renderer.js:94:9)
    at /Users/termosa/Source/feather-app/node_modules/stylus-loader/index.js:149:12
    at tryCatchReject (/Users/termosa/Source/feather-app/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/Users/termosa/Source/feather-app/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/Users/termosa/Source/feather-app/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/Users/termosa/Source/feather-app/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/Users/termosa/Source/feather-app/node_modules/when/lib/Scheduler.js:62:19)
 @ ./src/styles/main.styl 4:14-168 13:2-17:4 14:20-174
```

I've found some issues similar to this and they were related to the versions compability.
But I don't have enough time to fix now so I'll keep this issue here.

**Comment by termosa** [comment]
Thank you!
